nelmio_api_doc:
    areas:
        default:
            path_patterns:
                - ^/api/restaurantes
        doc:
            path_patterns:
                - ^/api/restaurantes
            security: []

